# -*- coding: utf-8 -*-
"""python Foundation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEEnpeZ5MEHfWk25jnFknocpbwydLDPL

print function---> display the op to the screen
"""

print("hello world")

"""end parameter --> is used to print two different statement in a same line"""

print("hello",end =" ")
print("world")

print("pyton",end="-")
print("programming")

"""'sep' parameter => is used to seperate a elements with specific operator"""

print("mango","apple","banana",sep=',')

"""input function --> it is used to get a input from a user,and display over the screen,user_input()"""

user_input = input("enter your name:")
print("HEY,my name is" + user_input)

"""data type=> nature of the data that any variable can hole"""

x = 10 #int
y =10.5 # float
z = 10+3j # complex
print(type(x))